### PR TITLE
Add smoke test utilities for the client

### LINKED ISSUE #606: Add smoke testing utilities for integration-testing a Tiled deployment
The function `tiled.client.tree` walks Tiled's data structure and touches every node. It would be useful to further have utilities that:

* read the data, in whole or in part
* export the data in each of the range of nominally supported formats
* more?

Perhaps something like:

```py
smoke_read(node)
smoke_export(node)
smoke_all(node)  # read and export and anything else we can think of
```

### PR DESCRIPTION
**Pull request by jmaruland**
This PR adds a group of methods to help test the integration of the datasets with a tiled server by making calls from the client and walking down the existing nodes. The goal is to automate a recursive method that identifies the correct nodes and applies the respective test feature to these nodes.
For the moment, we are adding read and export methods to smoke test the server.

Closes #606

### CODE REVIEW

**Comment by jmaruland** [comment]
This PR builds on #633, that PR should be merged first.

**Comment by danielballan** [comment]
Looks good, now just needs rebase

**Comment by jmaruland** [comment]
@danielballan I run the rebase by myself and without the training wheels this time. Was it run correctly? 
Also, the CI is throwing a new AssertionError that is unrelated to my PR and it's coming from `tiled/_tests/test_metrics.py::test_error_code - AssertionError`

**Comment by danielballan** [comment]
Power-cycled to rerun CI

**Pull request merged**
