### PR TITLE
Customize default uvicorn logging config to include authenticated user/service, correlation ID.

### PR DESCRIPTION
**Pull request by danielballan**
Log configuration can be customized (`--log-config`) and there is an `example_log_config.yml` in the repo, but I think it's worth changing the _default_ log configuration from base uvicorn defaults to one that includes timestamp and correlation ID.

Before:
```
$ tiled serve catalog --temp --api-key=secret
Creating catalog database at /tmp/tmp2cpih0xo/catalog.db
Creating writable catalog data directory at /tmp/tmp2cpih0xo/data
INFO:     Started server process [430162]
INFO:     Waiting for application startup.
Tiled version 0.1.0a123.dev17+gbd1c7c83.d20240525
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:45080 - "GET /api/v1/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:45080 - "GET /api/v1/metadata/?include_data_sources=false HTTP/1.1" 200 OK
```

After:
```
$ tiled serve catalog --temp --api-key=secret
Creating catalog database at /tmp/tmpec7fadbh/catalog.db
Creating writable catalog data directory at /tmp/tmpec7fadbh/data
[2024-05-25T08:51:45.347Z] [-] INFO:     Started server process [429720]
[2024-05-25T08:51:45.347Z] [-] INFO:     Waiting for application startup.
Tiled version 0.1.0a123.dev17+gbd1c7c83.d20240525
[2024-05-25T08:51:45.352Z] [-] INFO:     Application startup complete.
[2024-05-25T08:51:45.353Z] [-] INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
[2024-05-25T08:51:45.857Z] [82e09cc2c13a7330] INFO:     127.0.0.1:33004 - "GET /api/v1/ HTTP/1.1" 200 OK
[2024-05-25T08:51:45.937Z] [d8e2e8a70ea301c9] INFO:     127.0.0.1:33004 - "GET /api/v1/metadata/?include_data_sources=false HTTP/1.1" 200 OK
```

### Checklist
- [x] Add a Changelog entry
- [ ] Add the ticket number which this PR closes to the comment section

### CODE REVIEW

**Comment by danielballan** [comment]
I figured out how to thread the username through. Here is a single-user server. Notice `(public)` and `(admin)` in the log lines:

```
$ tiled serve catalog --temp --api-key=secret
Creating catalog database at /tmp/tmp5unjbua2/catalog.db
Creating writable catalog data directory at /tmp/tmp5unjbua2/data
[2024-05-25T09:40:07.744Z] [-] INFO:     Started server process [439625]
[2024-05-25T09:40:07.744Z] [-] INFO:     Waiting for application startup.
Tiled version 0.1.0a123.dev17+gbd1c7c83.d20240525
[2024-05-25T09:40:07.747Z] [-] INFO:     Application startup complete.
[2024-05-25T09:40:07.748Z] [-] INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
[2024-05-25T09:40:21.099Z] [-] INFO:     127.0.0.1:37348 (public) - "GET /api/v1/ HTTP/1.1" 200 OK
[2024-05-25T09:40:21.108Z] [-] INFO:     127.0.0.1:37348 (admin) - "GET /api/v1/metadata/?include_data_sources=false HTTP/1.1" 200 OK
```

And here is a multi-user server:

```
 ALICE_PASSWORD=secret BOB_PASSWORD=secret tiled serve config example_configs/toy_authentication.yml 
Using configuration from /home/dallan/Repos/bnl/tiled/example_configs/toy_authentication.yml
[2024-05-25T09:50:44.257Z] [-] INFO:     Started server process [441864]
[2024-05-25T09:50:44.257Z] [-] INFO:     Waiting for application startup.
Tiled version 0.1.0a123.dev17+gbd1c7c83.d20240525
Transient in-memory database initialized.
Ensuring that principal with identity {'provider': 'toy', 'id': 'alice'} has role 'admin'
[2024-05-25T09:50:44.387Z] [-] INFO:     Application startup complete.
[2024-05-25T09:50:44.388Z] [-] INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
[2024-05-25T09:50:49.660Z] [-] INFO:     127.0.0.1:34018 (public) - "POST /api/v1/auth/provider/toy/token HTTP/1.1" 401 Unauthorized
[2024-05-25T09:50:55.524Z] [-] INFO:     127.0.0.1:57162 (public) - "POST /api/v1/auth/provider/toy/token HTTP/1.1" 200 OK
[2024-05-25T09:50:58.780Z] [-] INFO:     127.0.0.1:57162 ('alice') - "GET /api/v1/search/?page%5Boffset%5D=0&fields=&sort=_ HTTP/1.1" 200 OK
[2024-05-25T09:51:01.818Z] [-] INFO:     127.0.0.1:57162 ('alice') - "GET /api/v1/metadata/A HTTP/1.1" 200 OK
[2024-05-25T09:51:07.086Z] [-] INFO:     127.0.0.1:60124 (public) - "POST /api/v1/auth/provider/toy/token HTTP/1.1" 200 OK
[2024-05-25T09:51:08.177Z] [-] INFO:     127.0.0.1:60124 ('bob') - "GET /api/v1/metadata/A HTTP/1.1" 200 OK
```

**Comment by dylanmcreynolds** [comment]
I have just upgrade a container from a117 to a122 and noticed that there was no uvicorn logging at all...just curious if that is a known issue?

**Review by dylanmcreynolds — APPROVED** [review]
I really like this change.

**Comment by danielballan** [comment]
> no uvicorn logging at all...just curious if that is a known issue?

Yes, regression in #730 fixed in commit https://github.com/bluesky/tiled/pull/750/commits/41888ae1598c3654fbcebea75b1876046e8ceced in this PR. I should have called that out in the PR description.

**Comment by dylanmcreynolds** [comment]
I love the correlationid and username on by default.

Most container engines have the option of printing time stamps as part of their logging facility. I assume that if the're storing timestamps anyway, then it slightly more efficient to not have uviron put them into the logs. Therere, should we consider making timestamps off the the default configuration?

`-t` options in [podman and docker](https://docs.podman.io/en/v4.4/markdown/podman-logs.1.html)

`-timestamps` option in [kubetcl logs](https://kubernetes.io/docs/reference/kubectl/generated/kubectl_logs/)

I think I'd love to have a command line argument to turn timestamps on in tiled, but leave the default to off.

**Comment by danielballan** [comment]
Good feedback @dylanmcreynolds, thanks. Latest removes timestamp by default. (It also removes the `INFO:    ` from the access logger, because the level is _always_ INFO and this wastes horizontal space.)

```
$ tiled serve catalog --temp
Creating catalog database at /tmp/tmpg036topq/catalog.db
Creating writable catalog data directory at /tmp/tmpg036topq/data

    Navigate a web browser or connect a Tiled client to:

    http://127.0.0.1:8000?api_key=8d39146f5c3e065bbc3167f26caee17885982a46bada12a435b2654f479847b4


[-] INFO:     Started server process [3187231]
[-] INFO:     Waiting for application startup.
Tiled version 0.1.0a118.dev72+gab075af3
[-] INFO:     Application startup complete.
[-] INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
[99668dc203caff78] 127.0.0.1:52560 (public) - "GET / HTTP/1.1" 200 OK
```

New CLI flag `--log-timestamps` puts timestamps on.

```
$ tiled serve catalog --temp --log-timestamps
Creating catalog database at /tmp/tmp_ne0_9b1/catalog.db
Creating writable catalog data directory at /tmp/tmp_ne0_9b1/data

    Navigate a web browser or connect a Tiled client to:

    http://127.0.0.1:8000?api_key=dc64f4dfb78cde67609b12235a97ae244101e3ab8750985ad8d18a53580b1caf


[2024-05-28T09:57:26.466Z] [-] INFO:     Started server process [3187669]
[2024-05-28T09:57:26.466Z] [-] INFO:     Waiting for application startup.
Tiled version 0.1.0a118.dev72+gab075af3
[2024-05-28T09:57:26.469Z] [-] INFO:     Application startup complete.
[2024-05-28T09:57:26.469Z] [-] INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
[2024-05-28T09:57:27.724Z] [34fdcd13b06540a6] 127.0.0.1:35986 (public) - "GET / HTTP/1.1" 200 OK
```

**Pull request merged**
