### PR TITLE
Revisit structures

### LINKED ISSUE #43: Support serializers on generic trees
These should include, for example hdf5.

### LINKED ISSUE #79: Test indexing thoroughly
```
In [7]: client.values_indexer[-100_000:-100_010]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-d6734c2be144> in <module>
----> 1 client.values_indexer[-100_000:-100_010]

~/Repos/bnl/tiled/tiled/trees/utils.py in __getitem__(self, key)
     23 
     24     def __getitem__(self, key):
---> 25         return self.fn(key)
     26 
     27 

~/Repos/bnl/tiled/tiled/trees/utils.py in _values_indexer(self, index_or_slice)
     95             return value
     96         elif isinstance(index_or_slice, slice):
---> 97             start, stop, direction = slice_to_interval(index_or_slice)
     98             return [value for _key, value in self._items_slice(start, stop, direction)]
     99         else:

~/Repos/bnl/tiled/tiled/trees/utils.py in slice_to_interval(slice_)
    111     if step == 1:
    112         if start < 0:
--> 113             raise ValueError(
    114                 "Tree sequence slices with start < 0 must have step=-1. "
    115                 f"Use for example [{slice_.start}:{slice_.stop}:-1]"

ValueError: Tree sequence slices with start < 0 must have step=-1. Use for example [-100000:-100010:-1](This is a limitation of slicing on Tree sequences that does not apply to Python sequences in general.)

In [8]: client.values_indexer[-100_000:-100_010:-1]
Out[8]: 
[<BlueskyRun {'primary'} scan_id=15564 uid='a6626d42' 2017-02-12 16:39>,
 <BlueskyRun {'primary'} scan_id=15563 uid='0bf7c3bc' 2017-02-12 16:39>,
 <BlueskyRun {'primary'} scan_id=15562 uid='b08e3d6e' 2017-02-12 16:39>,
 <BlueskyRun {'primary'} scan_id=15561 uid='c2013ec2' 2017-02-12 16:39>,
 <BlueskyRun {'primary'} scan_id=15560 uid='f3e30dcb' 2017-02-12 16:39>,
 <BlueskyRun {'primary'} scan_id=15559 uid='bbdb8e64' 2017-02-12 16:39>,
 <BlueskyRun {'primary'} scan_id=15558 uid='d4a41bf7' 2017-02-12 16:39>,
 <BlueskyRun {'primary'} scan_id=15557 uid='2ae15cf7' 2017-02-12 16:39>,
 <BlueskyRun {'primary'} scan_id=15556 uid='d0cea289' 2017-02-12 16:38>,
 <BlueskyRun {'primary'} scan_id=15555 uid='dccae2d8' 2017-02-12 16:38>]

In [9]: client.values_indexer[-100_000::-1]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-d1105e751fce> in <module>
----> 1 client.values_indexer[-100_000::-1]

~/Repos/bnl/tiled/tiled/trees/utils.py in __getitem__(self, key)
     23 
     24     def __getitem__(self, key):
---> 25         return self.fn(key)
     26 
     27 

~/Repos/bnl/tiled/tiled/trees/utils.py in _values_indexer(self, index_or_slice)
     96         elif isinstance(index_or_slice, slice):
     97             start, stop, direction = slice_to_interval(index_or_slice)
---> 98             return [value for _key, value in self._items_slice(start, stop, direction)]
     99         else:
    100             raise TypeError(

~/Repos/bnl/tiled/tiled/trees/utils.py in <listcomp>(.0)
     96         elif isinstance(index_or_slice, slice):
     97             start, stop, direction = slice_to_interval(index_or_slice)
---> 98             return [value for _key, value in self._items_slice(start, stop, direction)]
     99         else:
    100             raise TypeError(

~/Repos/bnl/tiled/tiled/client/node.py in _items_slice(self, start, stop, direction)
    390             sorting_params = self._reversed_sorting_params
    391         assert start >= 0
--> 392         assert stop >= 0
    393         next_page_url = f"{self.item['links']['search']}?page[offset]={start}"
    394         item_counter = itertools.count(start)

TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```

### LINKED ISSUE #94: Optimize access for small dataframes.
To access dataframes we do the following:

1. Request structure information about the column names and dtypes, via `/dataframe/meta/{path}` and the boundaries of the partitions of rows, via `/dataframe/divisions/{path}`.
2. Construct a dask dataframe based on this information.
3. In parallel, with threaded dask workers, download each partition.

For large dataframes, I believe this is optimal. For dataframes with a single partition that is being immediately pulled into memory, there is no point in requesting the structure information separately. We may as well directly request all the data up front. With only one partition, there is no opportunity to parallelize anyway.

We can insert logic here

https://github.com/bluesky/tiled/blob/25eaeee3c1abf945d1fd4037caeccc7cb4b12fb0/tiled/client/dataframe.py#L238

that if, `self.structure().macro.npartitions == 1`, circumvents all the dask-related code and instead directly requests the entire dataframe via

```py
# Fast path: download the entire dataframe using /dataframe/full/
content = self.context.get_content(
            f"/dataframe/full/{'/'.join(self.context.path_parts)}/{'/'.join(self._path)}",
            params=self._params,
            headers={"Accept": APACHE_ARROW_FILE_MIME_TYPE},
)
return deserialization_registry(
    "dataframe", APACHE_ARROW_FILE_MIME_TYPE, content
)
```

For dataframes that fit into a single partition, that should reduce the requests from three, as illustrated in the logs here:

```
In [14]: from tiled.client.utils import logger

In [15]: from tiled.client import from_uri

In [16]: c = from_uri("https://aimm.lbl.gov")

In [17]: entry = c['wanli']['021879']

In [18]: logger.setLevel("DEBUG")

In [19]: entry.read()
09:19:40.992 -> GET 'https://aimm.lbl.gov/dataframe/meta//wanli/021879' 'host:aimm.lbl.gov' 'accept:*/*' 'accept-encoding:gzip,blosc' 'connection:keep-alive' 'user-agent:python-httpx/0.19.0' 'x-base-url:https://aimm.lbl.gov/' 'cookie:tiled_csrf=_-UGSWEHSiuovfpaJSpWtc1yKGG3h8itnsYIYJSziAc' 'authorization:[redacted]'
09:19:41.542 <- 200 server:nginx/1.19.2 date:Mon, 11 Oct 2021 13:19:41 GMT content-type:vnd.apache.arrow.file content-length:831 connection:keep-alive etag:471f4564554afdf880b383023b124782 content-encoding:blosc vary:Accept-Encoding server-timing:acl;dur=0.0, pack;dur=0.9, compress;dur=0.0;ratio=3.0, app;dur=9.2 strict-transport-security:max-age=15724800; includeSubDomains
09:19:41.555 -> GET 'https://aimm.lbl.gov/dataframe/divisions//wanli/021879' 'host:aimm.lbl.gov' 'accept:*/*' 'accept-encoding:gzip,blosc' 'connection:keep-alive' 'user-agent:python-httpx/0.19.0' 'x-base-url:https://aimm.lbl.gov/' 'cookie:tiled_csrf=_-UGSWEHSiuovfpaJSpWtc1yKGG3h8itnsYIYJSziAc' 'authorization:[redacted]'
09:19:41.701 <- 200 server:nginx/1.19.2 date:Mon, 11 Oct 2021 13:19:41 GMT content-type:vnd.apache.arrow.file content-length:726 connection:keep-alive etag:f092aab3abd74baa99f61dfccc700e1b content-encoding:blosc vary:Accept-Encoding server-timing:acl;dur=0.1, pack;dur=0.8, compress;dur=0.1;ratio=1.9, app;dur=12.8 strict-transport-security:max-age=15724800; includeSubDomains
09:19:41.718 -> GET 'https://aimm.lbl.gov/dataframe/partition//wanli/021879?partition=0' 'host:aimm.lbl.gov' 'accept:vnd.apache.arrow.file' 'accept-encoding:gzip,blosc' 'connection:keep-alive' 'user-agent:python-httpx/0.19.0' 'x-base-url:https://aimm.lbl.gov/' 'cookie:tiled_csrf=_-UGSWEHSiuovfpaJSpWtc1yKGG3h8itnsYIYJSziAc' 'authorization:[redacted]'
09:19:41.822 <- 200 server:nginx/1.19.2 date:Mon, 11 Oct 2021 13:19:41 GMT content-type:vnd.apache.arrow.file content-length:6128 connection:keep-alive etag:2c837a8d6383970a8f752678a39fa377 content-encoding:blosc vary:Accept-Encoding server-timing:acl;dur=0.0, read;dur=2.0, tok;dur=0.2, pack;dur=1.1, compress;dur=0.1;ratio=1.6, app;dur=13.9 strict-transport-security:max-age=15724800; includeSubDomains
Out[19]: 
         energy        i0       tey      tfy    i0_alt
0    905.002000  168309.0   72321.0   3115.0  489360.0
1    905.506726  173413.0   76394.0   3240.0  516456.0
2    906.005774  169016.0   74148.0   3196.0  501296.0
3    906.574110  174328.0   76380.0   3244.0  516288.0
4    907.011777  164823.0   71447.0   3007.0  483252.0
..          ...       ...       ...      ...       ...
173  941.821128  159201.0  134208.0  30643.0  445328.0
174  942.010020  151232.0  124445.0  28098.0  417367.0
175  942.205738  152831.0  128421.0  28771.0  427984.0
176  942.401537  149699.0  125226.0  27976.0  419354.0
177  942.604174  151930.0  127967.0  28623.0  426281.0

[178 rows x 5 columns]
```

to a single request for `/dataframe/full/...`.

### PR DESCRIPTION
**Pull request by danielballan**
This will be a large PR making many interconnected changes to how we think about structure. It mostly simplifies and consolidates. I expect a net reduction in lines of code.

## Motivation

* Reduce the number of requests for common tasks. We are seeing high latency costs because we are being overly lazy about fetching structure information and attrs.
* Remove the last vestiges of the Catalog/DataSource distinction.
* Consolidate the HTTP endpoints.

## Checklist

- [x] In the server, we still have a vestigial distinction between "tree" (née Catalog) and "reader" (née DataSource). Consolidate this into "node". This lays track for being able to read all data below a given node in a single response.
- [x] Finish renaming "reader" to "adapter". (Soon they may write as well as read, so "adapter" is the better name.)
- [x] Also rename various tree adapters from `Tree` to `SomethingAdapter`. For example, `Tree` -> `DirectoryAdapter`. This describes what is does / what problem is solves better from a user point of view.
- [x] Consolidate TIFF code into one module --- a minor thing I've been meaning to do.
- [x] Place "dataframe" microstructure inline as Arrow (for msgpack) or base64-encoded Arrow (for JSON).
- [x] Fetch structure greedily and cache it rather than (re-)requesting it at read time. Add a field that the server can use to signal that the structure may change.
- [x] Consolidate "structured_array_generic" and "structured_array_tabular" into just "array". When a format isn't applicable, the server will give a 406.
- [x] Absorb `dims` into "array" and make "xarray_variable" just a `spec`.
- [x] Transmit nested dataset and data_array metadata in a single request.
- [x] Add `/node/full`. Serializers should include HDF5 to start.

<hr />

Closes #43 
Closes #94 
Closes #79

### CODE REVIEW

**Comment by danielballan** [comment]
Notes on latest thinking here:
- array gets optional dims and "variable" becomes a spec
- DataArrayAdapter and DatasetAdapter have _some_ but not all of the Tree API: no pagination of keys/values, no search (for now), but __getitem__ and metadata. __getitem__ should return _another adapter_ so that you can walk the path to get inside a Dataset or DataArray to the internal arrays with `/array/full` etc.
- It's OK that Tree doesn't implement [micro/macro]structure. Those methods answer the question "What's simplifying assumptions can I make to go fast?" and the answer for Tree is "None; I am very generic."

**Comment by danielballan** [comment]
Example of how we pay fewer requests:

```
In [11]: items = dict(c.items_indexer[:])  # Fetch all metadata and structure info in one request.
08:48:23.417 -> GET 'http://localhost:8000/node/search/?page%5Boffset%5D=0&sort=' 'host:localhost:8000' 'accept:application/x-msgpack' 'accept-encoding:gzip,blosc' 'connection:keep-alive' 'user-agent:python-httpx/0.21.1' 'x-base-url:http://localhost:8000/' 'cookie:tiled_csrf=9HsWlkGWp6q7qsOdr9ehVk_T5nkbe6xWyA5TW2rqxzg'
08:48:23.449 <- 200 date:Thu, 06 Jan 2022 13:48:22 GMT server:uvicorn cache-control:must-revalidate etag:d47994f37e312108da362c68865a22c7 content-length:1578 content-type:application/x-msgpack content-encoding:gzip vary:Accept-Encoding server-timing:tok;dur=0.3, pack;dur=0.1, compress;dur=0.4;ratio=7.6, app;dur=26.8

In [12]: items['short_table'].read()  # Short table costs one request
08:48:28.125 -> GET 'http://localhost:8000/dataframe/partition/short_table?partition=0' 'host:localhost:8000' 'accept:vnd.apache.arrow.file' 'accept-encoding:gzip,blosc' 'connection:keep-alive' 'user-agent:python-httpx/0.21.1' 'x-base-url:http://localhost:8000/' 'cookie:tiled_csrf=9HsWlkGWp6q7qsOdr9ehVk_T5nkbe6xWyA5TW2rqxzg'
08:48:28.140 <- 200 date:Thu, 06 Jan 2022 13:48:22 GMT server:uvicorn etag:f774bcd9d593309fcf2bad432ae117f2 content-length:3834 content-type:vnd.apache.arrow.file content-encoding:blosc vary:Accept-Encoding server-timing:read;dur=3.3, tok;dur=0.3, pack;dur=1.4, compress;dur=0.1;ratio=1.5, app;dur=11.7
Out[12]: 
              A         B         C
index                              
0      0.516982  1.033964  1.550946
1      0.201502  0.403004  0.604506
2      0.164006  0.328012  0.492019
3      0.726489  1.452978  2.179467
4      0.024818  0.049636  0.074453
...         ...       ...       ...
95     0.317470  0.634940  0.952411
96     0.877264  1.754529  2.631793
97     0.750878  1.501756  2.252635
98     0.059107  0.118214  0.177322
99     0.377005  0.754011  1.131016

[100 rows x 3 columns]

In [13]: items['long_table'].read()  # Long table costs one request per partition (in parallel via dask threaded workers)
08:48:36.887 -> GET 'http://localhost:8000/dataframe/partition/long_table?partition=0' 'host:localhost:8000' 'accept:vnd.apache.arrow.file' 'accept-encoding:gzip,blosc' 'connection:keep-alive' 'user-agent:python-httpx/0.21.1' 'x-base-url:http://localhost:8000/' 'cookie:tiled_csrf=9HsWlkGWp6q7qsOdr9ehVk_T5nkbe6xWyA5TW2rqxzg'
08:48:36.892 -> GET 'http://localhost:8000/dataframe/partition/long_table?partition=1' 'host:localhost:8000' 'accept:vnd.apache.arrow.file' 'accept-encoding:gzip,blosc' 'connection:keep-alive' 'user-agent:python-httpx/0.21.1' 'x-base-url:http://localhost:8000/' 'cookie:tiled_csrf=9HsWlkGWp6q7qsOdr9ehVk_T5nkbe6xWyA5TW2rqxzg'
08:48:36.898 -> GET 'http://localhost:8000/dataframe/partition/long_table?partition=2' 'host:localhost:8000' 'accept:vnd.apache.arrow.file' 'accept-encoding:gzip,blosc' 'connection:keep-alive' 'user-agent:python-httpx/0.21.1' 'x-base-url:http://localhost:8000/' 'cookie:tiled_csrf=9HsWlkGWp6q7qsOdr9ehVk_T5nkbe6xWyA5TW2rqxzg'
08:48:36.902 -> GET 'http://localhost:8000/dataframe/partition/long_table?partition=3' 'host:localhost:8000' 'accept:vnd.apache.arrow.file' 'accept-encoding:gzip,blosc' 'connection:keep-alive' 'user-agent:python-httpx/0.21.1' 'x-base-url:http://localhost:8000/' 'cookie:tiled_csrf=9HsWlkGWp6q7qsOdr9ehVk_T5nkbe6xWyA5TW2rqxzg'
08:48:36.906 -> GET 'http://localhost:8000/dataframe/partition/long_table?partition=4' 'host:localhost:8000' 'accept:vnd.apache.arrow.file' 'accept-encoding:gzip,blosc' 'connection:keep-alive' 'user-agent:python-httpx/0.21.1' 'x-base-url:http://localhost:8000/' 'cookie:tiled_csrf=9HsWlkGWp6q7qsOdr9ehVk_T5nkbe6xWyA5TW2rqxzg'
08:48:36.984 <- 200 date:Thu, 06 Jan 2022 13:48:35 GMT server:uvicorn etag:e866cb762d0caa73b0f0f97c8f6cf3c6 content-length:562575 content-type:vnd.apache.arrow.file content-encoding:blosc vary:Accept-Encoding server-timing:read;dur=22.8, tok;dur=2.5, pack;dur=11.5, compress;dur=0.8;ratio=1.1, app;dur=69.9
08:48:36.986 <- 200 date:Thu, 06 Jan 2022 13:48:35 GMT server:uvicorn etag:e6539168969abe1a69ecd89e46daae64 content-length:562656 content-type:vnd.apache.arrow.file content-encoding:blosc vary:Accept-Encoding server-timing:read;dur=18.7, tok;dur=3.0, pack;dur=11.2, compress;dur=1.0;ratio=1.1, app;dur=62.8
08:48:36.989 <- 200 date:Thu, 06 Jan 2022 13:48:35 GMT server:uvicorn etag:581b047d4bc0b2f0c334765a53c61aaf content-length:562727 content-type:vnd.apache.arrow.file content-encoding:blosc vary:Accept-Encoding server-timing:read;dur=16.7, tok;dur=2.8, pack;dur=13.6, compress;dur=0.9;ratio=1.1, app;dur=64.7
08:48:36.993 <- 200 date:Thu, 06 Jan 2022 13:48:35 GMT server:uvicorn etag:4bac55e8edce34a3184314fb565eb9e3 content-length:562659 content-type:vnd.apache.arrow.file content-encoding:blosc vary:Accept-Encoding server-timing:read;dur=17.8, tok;dur=4.0, pack;dur=20.1, compress;dur=0.7;ratio=1.1, app;dur=71.6
08:48:36.994 <- 200 date:Thu, 06 Jan 2022 13:48:35 GMT server:uvicorn etag:4373c6e27d4348c48ea034eaf6f8c885 content-length:562652 content-type:vnd.apache.arrow.file content-encoding:blosc vary:Accept-Encoding server-timing:read;dur=15.8, tok;dur=3.7, pack;dur=14.5, compress;dur=0.8;ratio=1.1, app;dur=66.0
Out[13]: 
              A         B         C
index                              
0      0.917189  1.834378  2.751567
1      0.679369  1.358738  2.038106
2      0.598930  1.197859  1.796789
3      0.897645  1.795289  2.692934
4      0.857732  1.715464  2.573196
...         ...       ...       ...
99995  0.816249  1.632498  2.448747
99996  0.033831  0.067662  0.101493
99997  0.024527  0.049055  0.073582
99998  0.547369  1.094739  1.642108
99999  0.168534  0.337069  0.505603

[100000 rows x 3 columns]
```

**Comment by danielballan** [comment]
Downloading everything below the root node as HDF5:

```
$ tiled serve pyobject --public tiled.examples.generated_minimal:tree
```

```
$ http :8000/node/full/ Accept:application/x-hdf5 > test.h5
```

Works as expected.

**Review by dylanmcreynolds — APPROVED** [review]
Good stuff! I've given a little feedback outside of this review on naming and results of a smoke test I did. We should make sure to add naming changes required config.yml files in the release notes.

**Pull request merged**
