### PR TITLE
Refactors pulled from #668

### PR DESCRIPTION
**Pull request by danielballan**
I've extracted some refactor / cleanup commits from #668. We can base the items on the critical path for flyscanning (appendable tables and update-able data sources) on this while we take our time working through the design considerations in #668.

### CODE REVIEW

**Review by padraic-shafer — COMMENTED** [review]
Looks good.  Most of the differences from #686 are union-specific files.  The rest are mostly related to `structures.container.ContainerStructure`

Then there are some remaining differences that I'll highlight in a PR to your PR branch.

**Comment by danielballan** [comment]
CI failures arise from a dask release. Fix in [52ec6b8](https://github.com/bluesky/tiled/pull/686/commits/52ec6b86907f77751348832a14a3e260f6287806).

**Comment by danielballan** [comment]
Hm, more breakage from dask here: https://github.com/bluesky/tiled/actions/runs/8249730000/job/22562754120#step:10:796

**Comment by danielballan** [comment]
The breakage from dask 2024-3 is substantial. We can't address this quickly, correctly, so I have pinned back dask in a separate PR, merged by @tacaswell. This PR has been rebased on that and should now pass CI :crossed_fingers: .

**Review by padraic-shafer — APPROVED** [review]
Ready to merge at your convenience.

**Pull request merged**
