### PR TITLE
improve docker

### PR DESCRIPTION
**Pull request by kleinhenz**
* update Dockerfile so sparse deps are cached
* don't copy whole source directory into container
* make gunicorn config configurable using GUNICORN_CONF env var
* require check that single_user_api_key is set even in public mode

### CODE REVIEW

**Review by danielballan — COMMENTED** [review]
Thanks for refurbishing this.

My only reservation is `GUNICORN_CONF`. I wish we didn't have to introduce a new env var. I wonder if we should defer to the gunicorn env var [`GUNICORN_CMD_ARGS`](https://docs.gunicorn.org/en/stable/configure.html) which can be used to point to a custom config location (among other things).

**Comment by kleinhenz** [comment]
I was following [this](https://github.com/tiangolo/uvicorn-gunicorn-docker/blob/master/docker-images/start.sh) from the tiangolo uvicorn-gunicorn docker container but happy to change if you would rather depend on the built in env vars.

**Comment by danielballan** [comment]
That’s good enough for me. Just an idle thought.

**Review by dylanmcreynolds — COMMENTED** [review]
Seems solid.

**Pull request merged**
