### PR TITLE
Update deprecated method imsave to imwrite

### PR DESCRIPTION
**Pull request by jmaruland**

### CODE REVIEW

**Comment by danielballan** [comment]
Confirmed that all usages of `imsave` are gone:

```
12:57 dallan@pop-os:tiled [fix-tifffile-imsave-method]$ git grep imsave
12:57 dallan@pop-os:tiled [fix-tifffile-imsave-method]$
```

**Comment by jmaruland** [comment]
Closes #219

**Comment by jmaruland** [comment]
> 

I run `git grep imsave` and did find more cases in the repo

**Comment by danielballan** [comment]
You did? Have you handled them all now? I don't see any.

**Comment by jmaruland** [comment]
I run this command locally and it returned an empty result. I guess this means I covered all the cases where `imsave` was being used.

**Pull request merged**
